app_name: fastapi-lab-app
app_port: 5000
app_host_port: 5000
app_container_name: "{{ app_name }}"
docker_image_tag: latest
restart_policy: unless-stopped

app_environment:
  ENVIRONMENT: development
  LOG_LEVEL: debug

health_check_retries: 30
health_check_delay: 2
health_endpoint: /health
