{{- if .Values.secrets.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "myapp.fullname" . }}-secret
  labels:
    {{- include "myapp.labels" . | nindent 4 }}
    app.kubernetes.io/component: secret
  annotations:
    helm.sh/resource-policy: keep
    {{- with .Values.secrets.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
type: Opaque
data:
  {{- range $key, $value := .Values.secrets.data }}
  {{ $key }}: {{ $value | b64enc | quote }}
  {{- end }}
stringData:
  {{- range $key, $value := .Values.secrets.stringData }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
{{- end }}
