replicaCount: 1

image:
  tag: dev

service:
  port: 8000
  targetPort: 8000

livenessProbe:
  httpGet:
    port: 8000

readinessProbe:
  httpGet:
    port: 8000

env:
  - name: APP_MODE
    value: "development"
  - name: LOG_LEVEL
    value: "debug"

configEnv:
  APP_NAME: "DevOps Info Service (DEV)"
  ENVIRONMENT: "development"
  FEATURE_VISITS: "true"
  FEATURE_METRICS: "true"
  LOG_FORMAT: "json"
  METRICS_PORT: "8000"
  DEBUG_MODE: "true"

resources:
  limits:
    cpu: 250m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi

persistence:
  enabled: true
  size: 50Mi
  accessMode: ReadWriteOnce
  storageClass: "standard"
  mountPath: /data
